import Sinope
import Result
import CBGPromise

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeNetworkClient : NetworkClient, Equatable {
    init() {
    }

    private(set) var getCallCount : Int = 0
    var getStub : ((URL, [String: String]) -> (Future<Result<Data, NSError>>))?
    private var getArgs : Array<(URL, [String: String])> = []
    func getReturns(_ stubbedValues: (Future<Result<Data, NSError>>)) {
        self.getStub = {(url: URL, headers: [String: String]) -> (Future<Result<Data, NSError>>) in
            return stubbedValues
        }
    }
    func getArgsForCall(_ callIndex: Int) -> (URL, [String: String]) {
        return self.getArgs[callIndex]
    }
    func get(_ url: URL, headers: [String: String]) -> (Future<Result<Data, NSError>>) {
        self.getCallCount += 1
        self.getArgs.append((url, headers))
        return self.getStub!(url, headers)
    }

    private(set) var putCallCount : Int = 0
    var putStub : ((URL, [String: String], Data) -> (Future<Result<Data, NSError>>))?
    private var putArgs : Array<(URL, [String: String], Data)> = []
    func putReturns(_ stubbedValues: (Future<Result<Data, NSError>>)) {
        self.putStub = {(url: URL, headers: [String: String], body: Data) -> (Future<Result<Data, NSError>>) in
            return stubbedValues
        }
    }
    func putArgsForCall(_ callIndex: Int) -> (URL, [String: String], Data) {
        return self.putArgs[callIndex]
    }
    func put(_ url: URL, headers: [String: String], body: Data) -> (Future<Result<Data, NSError>>) {
        self.putCallCount += 1
        self.putArgs.append((url, headers, body))
        return self.putStub!(url, headers, body)
    }

    private(set) var postCallCount : Int = 0
    var postStub : ((URL, [String: String], Data) -> (Future<Result<Data, NSError>>))?
    private var postArgs : Array<(URL, [String: String], Data)> = []
    func postReturns(_ stubbedValues: (Future<Result<Data, NSError>>)) {
        self.postStub = {(url: URL, headers: [String: String], body: Data) -> (Future<Result<Data, NSError>>) in
            return stubbedValues
        }
    }
    func postArgsForCall(_ callIndex: Int) -> (URL, [String: String], Data) {
        return self.postArgs[callIndex]
    }
    func post(_ url: URL, headers: [String: String], body: Data) -> (Future<Result<Data, NSError>>) {
        self.postCallCount += 1
        self.postArgs.append((url, headers, body))
        return self.postStub!(url, headers, body)
    }

    private(set) var deleteCallCount : Int = 0
    var deleteStub : ((URL, [String: String]) -> (Future<Result<Data, NSError>>))?
    private var deleteArgs : Array<(URL, [String: String])> = []
    func deleteReturns(_ stubbedValues: (Future<Result<Data, NSError>>)) {
        self.deleteStub = {(url: URL, headers: [String: String]) -> (Future<Result<Data, NSError>>) in
            return stubbedValues
        }
    }
    func deleteArgsForCall(_ callIndex: Int) -> (URL, [String: String]) {
        return self.deleteArgs[callIndex]
    }
    func delete(_ url: URL, headers: [String: String]) -> (Future<Result<Data, NSError>>) {
        self.deleteCallCount += 1
        self.deleteArgs.append((url, headers))
        return self.deleteStub!(url, headers)
    }

    static func reset() {
    }
}

func == (a: FakeNetworkClient, b: FakeNetworkClient) -> Bool {
    return a === b
}
