import Foundation
import Sinope
import Result
import CBGPromise

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeFeedsService : FeedsService, Equatable {
    init() {
    }

    private(set) var subscribeCallCount : Int = 0
    var subscribeStub : (([NSURL], String) -> (Future<Result<[NSURL], SinopeError>>))?
    private var subscribeArgs : Array<([NSURL], String)> = []
    func subscribeReturns(stubbedValues: (Future<Result<[NSURL], SinopeError>>)) {
        self.subscribeStub = {(feeds: [NSURL], authToken: String) -> (Future<Result<[NSURL], SinopeError>>) in
            return stubbedValues
        }
    }
    func subscribeArgsForCall(callIndex: Int) -> ([NSURL], String) {
        return self.subscribeArgs[callIndex]
    }
    func subscribe(feeds: [NSURL], authToken: String) -> (Future<Result<[NSURL], SinopeError>>) {
        self.subscribeCallCount += 1
        self.subscribeArgs.append((feeds, authToken))
        return self.subscribeStub!(feeds, authToken)
    }

    private(set) var unsubscribeCallCount : Int = 0
    var unsubscribeStub : (([NSURL], String) -> (Future<Result<[NSURL], SinopeError>>))?
    private var unsubscribeArgs : Array<([NSURL], String)> = []
    func unsubscribeReturns(stubbedValues: (Future<Result<[NSURL], SinopeError>>)) {
        self.unsubscribeStub = {(feeds: [NSURL], authToken: String) -> (Future<Result<[NSURL], SinopeError>>) in
            return stubbedValues
        }
    }
    func unsubscribeArgsForCall(callIndex: Int) -> ([NSURL], String) {
        return self.unsubscribeArgs[callIndex]
    }
    func unsubscribe(feeds: [NSURL], authToken: String) -> (Future<Result<[NSURL], SinopeError>>) {
        self.unsubscribeCallCount += 1
        self.unsubscribeArgs.append((feeds, authToken))
        return self.unsubscribeStub!(feeds, authToken)
    }

    private(set) var fetchCallCount : Int = 0
    var fetchStub : ((String, NSDate?) -> (Future<Result<(NSDate, [Feed]), SinopeError>>))?
    private var fetchArgs : Array<(String, NSDate?)> = []
    func fetchReturns(stubbedValues: (Future<Result<(NSDate, [Feed]), SinopeError>>)) {
        self.fetchStub = {(authToken: String, date: NSDate?) -> (Future<Result<(NSDate, [Feed]), SinopeError>>) in
            return stubbedValues
        }
    }
    func fetchArgsForCall(callIndex: Int) -> (String, NSDate?) {
        return self.fetchArgs[callIndex]
    }
    func fetch(authToken: String, date: NSDate?) -> (Future<Result<(NSDate, [Feed]), SinopeError>>) {
        self.fetchCallCount += 1
        self.fetchArgs.append((authToken, date))
        return self.fetchStub!(authToken, date)
    }

    static func reset() {
    }
}

func == (a: FakeFeedsService, b: FakeFeedsService) -> Bool {
    return a === b
}